# Generated by Django 3.1.5 on 2021-05-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('specialisation', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
