# Generated by Django 3.1.5 on 2021-05-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('remedesivir', models.IntegerField(default=0)),
                ('oxygen_tank', models.IntegerField(default=0)),
                ('beds', models.IntegerField(default=0)),
                ('isVaccineCenter', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(default='Your Gender', max_length=20),
        ),
        migrations.AddField(
            model_name='doctors',
            name='isUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctors',
            name='state',
            field=models.CharField(default='State', max_length=20),
        ),
        migrations.AddField(
            model_name='doctors',
            name='uprn_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='location',
            field=models.CharField(default='City Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(default='Your Name', max_length=30),
        ),
    ]
