# Generated by Django 3.1.5 on 2021-05-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210520_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.EmailField(default='Email', max_length=255),
        ),
        migrations.AddField(
            model_name='doctors',
            name='year_dob',
            field=models.IntegerField(default=1980),
        ),
    ]
