# Generated by Django 3.1.5 on 2021-05-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210521_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='age',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='location',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='specialisation',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='state',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='year_dob',
        ),
        migrations.AddField(
            model_name='doctors',
            name='city',
            field=models.CharField(default='City', max_length=20),
        ),
        migrations.AddField(
            model_name='doctors',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.CharField(default='-', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='locality',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='priceRange',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='speciality',
            field=models.CharField(default='-', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='type',
            field=models.CharField(default='-', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='url',
            field=models.URLField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
