# Generated by Django 3.1.5 on 2021-05-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210523_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='oxygen_tank',
            new_name='oxygenCount',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='remedesivir',
            new_name='remedesivirCount',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='isVaccineCenter',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='place',
        ),
        migrations.AddField(
            model_name='hospital',
            name='ambulance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='availableBedsCount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='coordinates',
            field=models.CharField(default='-', max_length=35),
        ),
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AddField(
            model_name='hospital',
            name='districtID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(default='abcd@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pincode',
            field=models.CharField(default='-', max_length=7),
        ),
        migrations.AddField(
            model_name='hospital',
            name='plasma_donor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialties',
            field=models.CharField(default='-', max_length=1400),
        ),
        migrations.AddField(
            model_name='hospital',
            name='stateID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='telephone',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='website',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
