# Generated by Django 3.1.5 on 2021-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210524_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='beds',
            new_name='avaialbleBedsCount',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='availableBedsCount',
        ),
        migrations.AddField(
            model_name='hospital',
            name='isVaccineCenter',
            field=models.BooleanField(default=False),
        ),
    ]
