# Generated by Django 3.1.5 on 2021-05-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210524_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
