# Generated by Django 3.1.5 on 2021-05-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_detect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detect',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
