# Generated by Django 3.1.5 on 2021-05-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210527_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detect',
            name='userID',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
